name: Generate Language Stats

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stefvuck/github-profile-language-analytics@v1.1.0
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: "leaderboard"
          output_path: "github-stats"
          exclude_languages: "HTML,CSS,HLSL,ShaderLab,SCSS,TeX,Dart,R,C,Swift,Solidity,Jupyter Notebook"
          include_forks: "false"
          dark_mode: "true"
