name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jstrieb/github-stats@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXCLUDED_LANGS: "HTML,CSS,Jupyter Notebook,HLSL,ShaderLab,SCSS,TeX,Dart,R,C,Swift,Solidity"
          EXCLUDE_FORKED_REPOS: true
